name: Submit to Winget Community Repo

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The release tag to submit
        required: true

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Winget Community Repo (Stable)
        uses: vedantmgoyal2009/winget-releaser@4614300d5812e5df91cb02ef0edbece623d5dea8
        with:
          identifier: Vendicated.Vencord
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: 'VencordInstallerCli\.exe'
          release-tag: ${{ inputs.tag || github.event.release.tag_name }}
          fork-user: shiggybot

      - name: Submit package to Winget Community Repo (PTB)
        uses: vedantmgoyal2009/winget-releaser@4614300d5812e5df91cb02ef0edbece623d5dea8
        with:
          identifier: Vendicated.Vencord.PTB
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: 'VencordInstallerCli\.exe'
          release-tag: ${{ inputs.tag || github.event.release.tag_name }}
          fork-user: shiggybot

      - name: Submit package to Winget Community Repo (Canary)
        uses: vedantmgoyal2009/winget-releaser@4614300d5812e5df91cb02ef0edbece623d5dea8
        with:
          identifier: Vendicated.Vencord.Canary
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: 'VencordInstallerCli\.exe'
          release-tag: ${{ inputs.tag || github.event.release.tag_name }}
          fork-user: shiggybot
